datos = [
    "abre youtube",
    "quiero entrar a youtube",
    "inicia google",
    "abre el bloc de notas",
    "ejecuta calculadora",
    "abre youtube",
    "abre google",
    "abre el navegador",
    "abre una página",
    "abre un sitio web",
    "quiero abrir algo",
    "puedes abrir una página",
    "abre una aplicación",
    "abre un programa",
    "inicia youtube",
    "inicia google",
    "inicia el navegador",
    "ejecuta calculadora",
    "abre calculadora",
    "abre la calculadora",
    "abre bloc de notas",
    "abre el bloc de notas",
    "abre notas",
    "abre un archivo",
    "abre una carpeta",
    "abre una ventana",
    "quiero entrar a youtube",
    "quiero entrar a google",
    "quiero acceder a una página",
    "entra a una página",
    "entra a youtube",
    "entra a google",
    "puedes iniciar un programa",
    "puedes ejecutar algo",
    "ejecuta un programa",
    "lanza una aplicación",
    "arranca un programa",
    "abre una aplicación de Windows",
    "abre una herramienta",
    "abre una página web",
    "abre internet",
    "abre el buscador",
    "abre chrome",
    "abre edge",
    "abre mi navegador",
    "quiero usar youtube",
    "quiero usar google",
    "necesito abrir algo",
    "ayúdame a abrir algo",
    "puedes abrir youtube por mí",
    "puedes abrir google por mí",
    "abre el programa",
    "abre la aplicación",
    "ejecuta la aplicación",
    "quiero iniciar algo",
    "inicia una aplicación",
    "pon en marcha un programa",
]

