datos =[
    "qué puedes hacer",
        "que haces",
        "ayúdame",
        "dime tus funciones",
        "muéstrame la ayuda",
        "ayuda",
        "necesito ayuda",
        "puedes ayudarme",
        "me puedes ayudar",
        "ayúdame",
        "ayudame",
        "quiero ayuda",
        "necesito que me ayudes",
        "puedes echarme una mano",
        "me ayudas por favor",
        "ayúdame por favor",
        "ayudame por favor",
        "qué puedes hacer",
        "que puedes hacer",
        "qué sabes hacer",
        "que sabes hacer",
        "cuáles son tus funciones",
        "cuales son tus funciones",
        "dime tus funciones",
        "muéstrame tus funciones",
        "muestrame tus funciones",
        "qué funciones tienes",
        "que funciones tienes",
        "para qué sirves",
        "para que sirves",
        "qué haces",
        "que haces",
        "qué puedes hacer por mí",
        "que puedes hacer por mi",
        "enséñame tus capacidades",
        "muestra tus capacidades",
        "muéstrame la ayuda",
        "muestrame la ayuda",
        "abre la ayuda",
        "quiero ver la ayuda",
        "cómo me puedes ayudar",
        "como me puedes ayudar",
        "qué opciones tienes",
        "que opciones tienes",
        "qué comandos tienes",
        "que comandos tienes",
        "muéstrame los comandos",
        "muestrame los comandos",
        "lista de comandos",
        "qué puedo pedirte",
        "que puedo pedirte",
        "explícame lo que haces",
        "explicame lo que haces",
        "infórmame de tus funciones",
        "informame de tus funciones",
        "dame asistencia",
        "necesito asistencia",
]
