datos = [
"busca información sobre inteligencia artificial",
    "quiero buscar algo en internet",
    "investiga sobre Arduino",
    "busca información",
    "busca informacion",
    "quiero buscar algo",
    "necesito buscar algo",
    "puedes buscar en internet",
    "busca en internet",
    "abre una búsqueda",
    "realiza una búsqueda",
    "haz una búsqueda",
    "quiero investigar algo",
    "investiga esto",
    "investiga sobre un tema",
    "busca sobre inteligencia artificial",
    "busca sobre Arduino",
    "busca sobre programación",
    "encuentra información",
    "encuentra datos sobre esto",
    "ayúdame a buscar",
    "ayudame a buscar",
    "puedes investigar",
    "quiero que investigues",
    "consulta internet",
    "consulta información",
    "revisa internet",
    "mira en internet",
    "encuentra esto",
    "localiza información",
    "necesito información",
    "dame información sobre",
    "quiero saber sobre",
    "qué sabes de",
    "que sabes de",
    "averigua esto",
    "averigua sobre",
    "comprueba información",
    "búscame algo",
    "buscame algo",
    "búscame información",
    "buscame informacion",
    "hazme una búsqueda",
    "hazme una busqueda",
    "puedes encontrar esto",
    "quiero encontrar algo",
    "buscar datos",
    "buscar información en la web",
    "buscar en google",
    "abre google y busca",
    "realiza una investigación",
    "quiero una investigación",
    "necesito investigar",
    "investiga en la web",
    "busca por mí",
]


