datos = [
    "recuérdame hacer la tarea",
    "ponme un recordatorio",
    "recuérdame algo",
    "recuerdame algo",
    "crea un recordatorio",
    "crear un recordatorio",
    "pon un recordatorio",
    "añade un recordatorio",
    "agrega un recordatorio",
    "quiero crear un recordatorio",
    "necesito un recordatorio",
    "guarda un recordatorio",
    "hazme un recordatorio",
    "puedes recordarme algo",
    "quiero que me recuerdes algo",
    "necesito que me recuerdes algo",
    "avísame después",
    "avisame despues",
    "avísame mañana",
    "avisame mañana",
    "avísame más tarde",
    "avisame mas tarde",
    "recuérdame mañana",
    "recuerdame mañana",
    "recuérdame luego",
    "recuerdame luego",
    "no olvides recordarme",
    "programa un aviso",
    "programa un recordatorio",
    "crea una alarma",
    "pon una alarma",
    "haz una alarma",
    "quiero una alerta",
    "crea una alerta",
    "ponme una alerta",
    "guarda una tarea",
    "añade una tarea pendiente",
    "agrega una tarea pendiente",
    "recuerda hacer algo",
    "recuérdame estudiar",
    "recuerdame estudiar",
    "recuérdame llamar a alguien",
    "recuerdame llamar a alguien",
    "quiero que me avises",
    "necesito que me avises",
    "crea un aviso",
    "pon un aviso",
    "genera un recordatorio",
    "nuevo recordatorio",
    "registrar recordatorio"
]