datos = [
    "elimina un recordatorio",
    "eliminar un recordatorio",
    "borra un recordatorio",
    "borrar un recordatorio",
    "quita un recordatorio",
    "quitar un recordatorio",
    "elimina mis recordatorios",
    "borra mis recordatorios",
    "quiero eliminar un recordatorio",
    "quiero borrar un recordatorio",
    "necesito quitar un recordatorio",
    "cancela un recordatorio",
    "cancelar un recordatorio",
    "anula un recordatorio",
    "desactiva un recordatorio",
    "quitar aviso",
    "eliminar aviso",
    "borrar aviso",
    "cancela mi aviso",
    "borra mi aviso",
    "elimina mi aviso",
    "quita mi aviso",
    "quiero borrar una tarea",
    "elimina una tarea",
    "eliminar una tarea pendiente",
    "borra una tarea pendiente",
    "quita una tarea pendiente",
    "cancela una tarea",
    "cancelar una tarea",
    "borra una tarea guardada",
    "elimina una tarea guardada",
    "quita algo de mis recordatorios",
    "borra algo de mi lista",
    "elimina algo de mi lista",
    "limpia mis recordatorios",
    "vacía mis recordatorios",
    "quita todos los recordatorios",
    "borra todos los recordatorios",
    "elimina todos los avisos",
    "cancelar todos los avisos",
    "borra este recordatorio",
    "elimina este recordatorio",
    "quita este recordatorio",
    "ya no necesito este recordatorio",
    "no quiero este recordatorio",
    "olvida este recordatorio",
    "descarta este recordatorio",
    "remueve un recordatorio",
    "retira un recordatorio"
]