datos =["dime la hora",
    "que hora es",
    "dime la hora",
    "qué hora es",
    "que hora es",
    "me puedes decir la hora",
    "puedes decirme la hora",
    "quiero saber la hora",
    "sabes qué hora es",
    "sabes que hora es",
    "qué hora tenemos",
    "que hora tenemos",
    "qué hora marca el reloj",
    "que hora marca el reloj",
    "mira la hora",
    "verifica la hora",
    "consulta la hora",
    "necesito saber la hora",
    "ayúdame con la hora",
    "cuál es la hora actual",
    "cual es la hora actual",
    "qué hora es ahora",
    "que hora es ahora",
    "dime el tiempo",
    "qué tiempo es",
    "me dices la hora",
    "puedes mirar la hora",
    "quiero conocer la hora",
    "indícame la hora",
    "indica la hora",
    "muéstrame la hora",
    "muestrame la hora",
    "cuánto marca la hora",
    "cuanto marca la hora",
    "qué hora tienes",
    "que hora tienes",
    "tienes la hora",
    "tienes hora",
    "hora actual",
    "hora del día",
    "hora de hoy",
    "dime la hora exacta",
    "cuál es la hora exacta",
    "cual es la hora exacta",
    "puedes revisar la hora",
    "revisa la hora",
    "comprueba la hora",
    "cuánto tiempo es",
    "cuanto tiempo es",
    "qué hora será",
    "que hora será",
    "necesito la hora",
    "quiero la hora",
    "hora por favor",#53
    ]


