datos = [
    "qué recuerdas",
    "que recuerdas",
    "muéstrame tus recuerdos",
    "muestrame tus recuerdos",
    "enséñame lo que recuerdas",
    "enseñame lo que recuerdas",
    "dime mi información guardada",
    "qué tienes guardado",
    "que tienes guardado",
    "mira tu memoria",
    "revisa tu memoria",
    "abre la memoria",
    "lista mis recuerdos",
    "cuáles son mis recuerdos",
    "cuales son mis recuerdos",
    "muéstrame mi memoria",
    "muestrame mi memoria",
    "ver mi memoria",
    "quiero ver mi memoria",
    "abre mi memoria",
    "consulta mi memoria",
    "revisa mi memoria",
    "mira mis recuerdos",
    "ver mis recuerdos",
    "muéstrame la información guardada",
    "muestrame la información guardada",
    "dime qué tienes guardado",
    "dime que tienes guardado",
    "qué información tienes de mí",
    "que información tienes de mi",
    "qué datos recuerdas de mí",
    "que datos recuerdas de mi",
    "qué cosas sabes de mí",
    "que cosas sabes de mi",
    "enséñame lo que sabes de mí",
    "enseñame lo que sabes de mi",
    "quiero saber qué recuerdas",
    "quiero saber que recuerdas",
    "muéstrame lo que recuerdas",
    "muestrame lo que recuerdas",
    "dime mis recuerdos",
    "ver información almacenada",
    "mostrar memoria",
    "muéstrame la memoria",
    "muestrame la memoria",
    "comprueba mi memoria",
    "comprueba tus recuerdos",
    "revisa los datos guardados",
    "qué has guardado",
    "que has guardado",
    "qué sabes sobre mí",
    "que sabes sobre mi",
    "quiero consultar mis datos",
    "consulta mis recuerdos",
    "abre los recuerdos",
    "enséñame la memoria",
    "ver datos guardados",
    "mostrar recuerdos"
]


