datos = [
    "muéstrame mis recordatorios",
    "muestrame mis recordatorios",
    "qué recordatorios tengo",
    "que recordatorios tengo",
    "enséñame mis recordatorios",
    "enseñame mis recordatorios",
    "ver mis recordatorios",
    "quiero ver mis recordatorios",
    "abre mis recordatorios",
    "consulta mis recordatorios",
    "revisa mis recordatorios",
    "dime mis recordatorios",
    "cuáles son mis recordatorios",
    "cuales son mis recordatorios",
    "qué tengo pendiente",
    "que tengo pendiente",
    "muestra mis tareas",
    "muéstrame mis tareas",
    "muestrame mis tareas",
    "lista mis recordatorios",
    "lista mis tareas",
    "ver lista de recordatorios",
    "quiero consultar mis avisos",
    "consulta mis avisos",
    "qué avisos tengo",
    "que avisos tengo",
    "muéstrame mis avisos",
    "muestrame mis avisos",
    "revisa mis tareas pendientes",
    "ver tareas pendientes",
    "qué debo hacer",
    "que debo hacer",
    "qué tengo para recordar",
    "que tengo para recordar",
    "muéstrame lo pendiente",
    "muestrame lo pendiente",
    "dime las cosas pendientes",
    "ver mis pendientes",
    "consulta mis pendientes",
    "abre la lista de recordatorios",
    "enséñame la lista de recordatorios",
    "quiero ver mis tareas guardadas",
    "muestra mis tareas guardadas",
    "qué guardé para después",
    "que guarde para despues",
    "hay algún recordatorio",
    "hay algun recordatorio",
    "tengo recordatorios"
]