datos = [
    "recuerda que mi color favorito es azul",
    "guarda esto en tu memoria",
    "quiero que recuerdes algo",
    "memoriza esto",
    "puedes recordar algo",
    "necesito que recuerdes algo",
    "añade esto a tu memoria",
    "agrega esto a tu memoria",
    "guarda un recuerdo",
    "crea un recuerdo",
    "quiero guardar información",
    "guarda información",
    "recuerda mi nombre",
    "recuerda mi color favorito",
    "recuerda mi cumpleaños",
    "recuerda este dato",
    "no olvides esto",
    "no lo olvides",
    "ten esto presente",
    "apunta esto",
    "guarda este dato",
    "almacena esto",
    "registra esto",
    "quiero que lo guardes",
    "quiero que lo memorices",
    "puedes guardar datos",
    "puedes recordar información"
]