datos = ["saluda",
    "buenas",
    "hola",
    "buenos dias",
    "buenas tardes",
    "buenas noches",
    "saluda",
    "qué tal",
    "cómo estás",
    "todo bien",
    "me alegra verte",
    "hey",
    "hola",
    "buenas",
    "buenos días",
    "buenos dias",
    "buenas tardes",
    "buenas noches",
    "hey",
    "hola qué tal",
    "hola que tal",
    "qué tal",
    "que tal",
    "cómo estás",
    "como estas",
    "cómo te va",
    "como te va",
    "cómo estás hoy",
    "como estas hoy",
    "qué haces",
    "que haces",
    "qué hay",
    "que hay",
    "qué cuentas",
    "que cuentas",
    "cómo va todo",
    "como va todo",
    "todo bien",
    "todo está bien",
    "espero que estés bien",
    "me alegra verte",
    "un gusto conocerte",
    "mucho gusto",
    "encantado de conocerte",
    "es un placer conocerte",
    "qué gusto hablar contigo",
    "qué gusto verte",
    "hola amigo",
    "hola asistente",
    "hola Arche",
    "hola inteligencia artificial",
    "saludos",
    "un saludo",
    "te saludo",
    "quiero saludarte",
    "venía a saludarte",
    "solo pasaba a saludar",
    "buen día",
    "feliz día",
    "buen inicio de día",
    "buenas noches Arche",
    "hola de nuevo",
    "volví",
    "ya regresé",#63
    ]
